spring:
  application:
    name: analytics-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/analytics}
    username: ${SPRING_DATASOURCE_USERNAME:analytics}
    password: ${SPRING_DATASOURCE_PASSWORD:analytics}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
grpc:
  client:
    orderAggregation:
      address: ${ORDER_GRPC_TARGET:static://localhost:9090}
      enableKeepAlive: true
      negotiationType: PLAINTEXT

server:
  port: ${SERVER_PORT:8081}
